<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Transaksi</name>
   <tag></tag>
   <elementGuidId>1dc91c21-5490-421c-9a20-e87d4e3167e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.v-list-item__title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='list-item-1489']/div[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[1]/div[2]/div/div[1]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div[2]/div/div[1]/div[2]</value>
      <webElementGuid>5e40b4fe-64da-499c-b4ab-1a09fa4b537a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list-item-1489']/div[2]</value>
      <webElementGuid>0380599a-60be-4feb-8dd3-c71b38e293c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beli'])[468]/following::div[5]</value>
      <webElementGuid>df810bce-f75b-40c2-ad87-66f7786bd260</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail'])[468]/following::div[5]</value>
      <webElementGuid>b899fdb3-01b3-45a3-9a67-b4ae7b2c03b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/preceding::div[2]</value>
      <webElementGuid>283430e1-bd6e-470c-bf18-dc84992c4361</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'list-item-1489', '&quot;', ')/div[@class=', '&quot;', 'v-list-item__title', '&quot;', ']')])[1]/preceding::div[4]</value>
      <webElementGuid>16667889-8d22-427c-8911-6a86660fe614</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Transaksi']/parent::*</value>
      <webElementGuid>e6ee1e70-6224-47c7-ad22-5de490d612b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]</value>
      <webElementGuid>c848e725-ae00-4a1e-b6db-d8e71216ed32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Transaksi ' or . = ' Transaksi ')]</value>
      <webElementGuid>a1cf48f5-1dc6-4528-8868-d7d9699d2200</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
