<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_input-32</name>
   <tag></tag>
   <elementGuidId>4b4108e1-b6aa-4b5d-a119-f9b7eaa74fc1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-32</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-32']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[1]/div/main/div/div/div/div[2]/form/div[2]/div/div[1]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div/main/div/div/div/div[2]/form/div[2]/div/div[1]/div/input</value>
      <webElementGuid>e29a95d1-afff-420e-b692-eaf9b7569561</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-32']</value>
      <webElementGuid>809c85eb-ee54-4539-8d5f-e88ec9624388</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div[2]/div/div/div/input</value>
      <webElementGuid>e45ec814-7b14-423a-9674-2adde0689440</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>8da1cfd3-a49d-4599-8448-4122f096737f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-32' and @type = 'text']</value>
      <webElementGuid>e617f5e3-4ff4-4c96-b646-7c4bf035e324</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
